### ISSUE TITLE
Provider does not understand user's status 'Pending user action'

### ISSUE THREAD

**Issue by mszewczyk-ipwt** [pulumi/pulumi-okta#100]
provider reports resource error during refresh:
```
error: okta:user/user:User resource 'user' has a problem: expected [{{} status}] to be one of ACTIVE,STAGED,DEPROVISIONED,SUSPENDED, got PROVISIONED. Examine values at 'User.Status'.
```

## Expected behavior
Status of the user should be refreshed with no errors

## Current behavior
error reported like above

## Steps to reproduce
1. Create a user using User class in `okta.user` provider with no `password` - okta sends emails when no password is provided.
2. After first update user's status on page is 'Pending user action'.
3. Refresh the stack with that user's status.

## Context (Environment)
Using Python:
```► venv/bin/python --version
Python 3.9.2
```
Okta provider:
```
NAME        KIND      VERSION  SIZE    INSTALLED  LAST USED
okta        resource  3.0.0    42 MB   n/a        1 hour ago
```
Pulumi:
```
► pulumi version
v3.2.1
```

## Affected feature
I am using pulumi to automte the process of creating users and in every procedure I refresh the status of the users. When not supported status appears then no action is taken and the process results in exit code 1.

**Comment by mjeffryes** [comment]
Unfortunately, it looks like this issue hasn't seen any updates in a while. If you're still encountering this problem, could you leave a quick comment to let us know so we can prioritize it?
