### ISSUE TITLE
Can't create authenticator if it was not previous configured in Okta UI

### ISSUE THREAD

**Issue by rodriguesgm** [pulumi/pulumi-okta#191]
### What happened?

I'm trying to configure Google Authenticator with the following code but it's not working. I'm in a new Okta environment so if I call `GET /api/v1/authenticators` I don't see the `google_otp` or any other non default authenticator like `rsa_token`, etc, which I guess it's normal, because they are not configured yet. So, when trying to configure it (create this authenticator resource) it raises an error saying the authenticator does not exists.

```
// Pulumi js code to create the authenticator
new okta.Authenticator('google-auth', {
    key: 'google_otp',
});
```

If I go to the Okta Admin console, and manually add the Google Authenticator and then delete it, when calling `GET /api/v1/authenticators` I now see the authenticator being returned in the response but as `INACTIVE`. If I run the same pulumi code to create the resource, now it works.

So basically, the `new okta.Authenticator()` only works for authenticators that are in the response of `GET /api/v1/authenticators`

### Steps to reproduce

In a new Okta Environment just try to create an authenticator for `google_otp` or any other resource not returned by `GET /api/v1/authenticators`

### Expected Behavior

The authenticator should be created instead of getting the error `authenticator with key 'google_otp' does not exist`

### Actual Behavior

I'm getting the following error for any authenticator that was not previously configured in the UI, like `google_otp`, `rsa_token`, `yubikey_token`

```
// result
error: 1 error occurred:
        * authenticator with key '****' does not exist
```

### Versions used

pulumi version: v2.11.2
@pulumi/okta: 3.7.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Unfortunately, we're limited by what the API supports here. Consider filing an issue with Okta to add new types to the API?
