### ISSUE TITLE
Update the value for a "sub" claim 

### ISSUE THREAD

**Issue by NArnott** [pulumi/pulumi-okta#212]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

For a given Okta Authorization Server, we can create new claims using the ServerClaim resource. However, Okta has one default claim called "sub" that cannot be deleted or modified, except for the Value. I need a way for Pulumi to update the Value for that imbedded claim type so I can change what it does.

![image](https://user-images.githubusercontent.com/198647/180859215-6ec7e79b-8366-4a58-a1fa-044f94d5f348.png)

**Comment by viveklak** [comment]
I am not the most well-versed with Okta so apologies in advance if this wrong, but I feel https://www.pulumi.com/registry/packages/okta/api-docs/authserverclaimdefault/ is what you are looking for?

**Comment by NArnott** [comment]
If it is, the description for it "This resource allows you to configure Default Authorization Server Claims." doesn't seem right. It sounds like it would allow you to set all claims on the default Auth Server. However, based on the example, maybe it is meant to do what I'm looking for.

**Comment by NArnott** [comment]
Looks like that was it. The docs was a bit confusing, but it did solve my issue. Thanks, @viveklak!
