### ISSUE TITLE
No acceptance tests running in CI for okta

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-okta#312]
### What happened?

```
  examples_test.go:15: Skipping test due to missing OKTA_API_TOKEN variable
```

### Expected Behavior

At least one acc tests running.

### Steps to reproduce

See CI

### Output of `pulumi about`

N/A

### Additional context

This blocks releases.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aq17** [comment]
Closing this as completed thanks to https://github.com/pulumi/pulumi-okta/pull/309.
