### ISSUE TITLE
Setting apiToken through config not encrypted in state file

### ISSUE THREAD

**Issue by mdop-wh** [pulumi/pulumi-okta#32]
Setting the apiToken through pulumi config like so
```
pulumi config set --secret okta:apiToken ZZZZZZ
```
does not flag the apiToken as a secret on the default okta provider. The apiKey is then stored unencrypted in the state file. 

Im unsure if this is a limitation of pulumi-terraform-bridge or how it can be treated as a secret.

https://github.com/pulumi/pulumi-okta/blob/67aa31c7329e29de2426e25fc3df0c42ed8512f7/sdk/go/okta/config/config.go#L13

I think replacing this line with `.TrySecret` but unsure how all of this code is generated.

**Comment by mdop-wh** [comment]
I think maybe this can be closed based on the release notes for pulumi 2.14.0:

> Propagate secretness of provider configuration through to the statefile. This ensures that any configuration values marked as secret (i.e. values set with pulumi config set --secret) that are used as inputs to providers are encrypted before they are stored. #5742

**Comment by lukehoban** [comment]
@mdop-wh Yes - indeed it should. This was fixed with https://github.com/pulumi/pulumi/pull/5742.  Closing now.
