### ISSUE TITLE
DOCS - Pulumi import instructions removed / missing from documentation

### ISSUE THREAD

**Issue by SMSMichael** [pulumi/pulumi-okta#467]
### What happened?

It looks like that the instructions in the Pulumi Okta provider docs for leveraging `pulumi import` for Okta resources was removed in #410.  This documentation section was extremely useful - can someone help me understand whether this section was removed from the docs intentionally or not?  If not, please restore this section to the documentation.  Thanks!

### Example

This page (https://www.pulumi.com/registry/packages/okta/api-docs/app/saml/) used to include a section titled `import` with instructions and code snippets for importing existing Okta resources into the Pulumi stack.  The current version of the page is missing the import instructions and section.  This appears to have been removed from all Okta resource docs.

### Output of `pulumi about`

CLI
Version      3.67.0  
Go Version   go1.20.4
Go Compiler  gc      

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045  
Arch     x86_64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/**********
User           **********
Organizations  **********

### Additional context

Love the docs - hoping this was just an oversight and we can get this section restored quickly.  Thanks!

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @SMSMichael. Our docs are generated from upstream, and this looks like a bug in the scraping. Thanks for letting us know!

**Comment by iwahbe** [comment]
This has been resolved. Okta resources now have import sections with instructions.
