### ISSUE TITLE
TypeError: pulumi.runtime.registerResourceModule is not a function

### ISSUE THREAD

**Issue by simonlevy5** [pulumi/pulumi-okta#77]
I get the following error when I add the `@pulumi/okta` and run a Pulumi program:
```
error: Running program '/Users/simon/workspace/aws-typescript/test-runner' failed with an unhandled exception:
    TypeError: pulumi.runtime.registerResourceModule is not a function
        at Object.<anonymous> (/Users/simon/workspace/aws-typescript/node_modules/@pulumi/app/index.ts:75:16)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
        at Module.load (internal/modules/cjs/loader.js:863:32)
        at Function.Module._load (internal/modules/cjs/loader.js:708:14)
        at Module.require (internal/modules/cjs/loader.js:887:19)
        at require (internal/modules/cjs/helpers.js:74:18)
        at Object.<anonymous> (/Users/simon/workspace/aws-typescript/node_modules/@pulumi/index.ts:13:1)
        at Module._compile (internal/modules/cjs/loader.js:999:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

To reproduce this all I needed to do was create a configured okta.Provider and run `pulumi up`. The following code example demonstrates what i'm doing:

```
import * as pulumi from "@pulumi/pulumi";
import * as okta from "@pulumi/okta";

const config = new pulumi.Config();
const oktaProvider = new okta.Provider("myOktaProvider", {
  apiToken: config.require("oktaApiToken"),
  baseUrl: config.require("oktaBaseUrl"),
  orgName: config.require("oktaOrgName")
});
```
All of the configuration values are set to valid values.

I'm have the following dependencies:
```
        "@pulumi/aws": "^3.23.0",
        "@pulumi/awsx": "^0.22.0",
        "@pulumi/okta": "^2.7.1",
        "@pulumi/postgresql": "^2.5.2",
        "@pulumi/pulumi": "^2.17.2",
        "@pulumi/random": "^3.0.0",
        "@pulumi/tls": "^3.0.0",
```
I am currently running Pulumi on macOS version 2.17.2

**Comment by simonlevy5** [comment]
FWIW it looks like the provider schema is using an old dependency (`@pulumi/pulumi` v2.0.0) that doesn't have the registerResourceModule method yet (looks like that appeared in v2.13 of the `@pulumi/pulumi` lib

Line here:
https://github.com/pulumi/pulumi-okta/blob/d72f0d5f4e170f33c260a3edea9b00355c3af503/provider/cmd/pulumi-resource-okta/schema.json#L17515

I am completely unfamiliar with the build system being used here (i'm just a consumer of Pulumi) but that looks suspicious

**Comment by leezen** [comment]
That's correct that that functionality should only exist after 2.13. But from your dependencies, the resolutions should work out such that `@pulumi/pulumi` is at least 2.17.2. Do you mind running `yarn why @pulumi/pulumi` to see if there's something bringing in an older version of `@pulumi/pulumi`? Alternatively, I would suggest checking if `yarn.lock` or `package-lock.json` has an older `@pulumi/pulumi` for whatever reason and correcting that, then removing your `node_modules` and reinstalling dependencies.

**Comment by simonlevy5** [comment]
@leezen 🙌  that was it - I had two modules using v2.10 (okta and postgresql)

Hard resetting my dependencies did the trick. I'll happily close this issue. Thank you
